spring.application.name=myfirstapp_rev
logging.level.org.springframework=debug
logging.level.com.revise.myfirstapp_rev.controller=debug
spring.profiles.active=dev
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
